version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_app
    ports:
      - "5432:5432"
